### ISSUE TITLE
Tapping ESC key triggers F15 in Autohotkey

### ISSUE THREAD

**Issue by LuisSanchez-Dev** [cajhin/capsicain#13]
First of all this program is so cool!

I got an issue where hitting the ESC key triggers the F15 key, I tested it with an AHK script containing `F15::RButton` and when tapping ESC it triggers a right click.

Let me know what other information I can help you with. Thanks a lot.

**Comment by cajhin** [comment]
Hi

I use F14/F15 to trigger my own special commands in AKH (e.g. my AHK gives me 10 clipboards).

In the capsicain 'master' branch (v61 or older), tapping ESC blindly releases all modifiers and F14/F15 (means: ESC sends a "key up" event for all those keys, just in case they are permanently down because the ini config is inconsistent). I'm surprised that 'key up' triggers "F15::RButton".

The next version (dev branch) is already smarter; now only keys that are actually inconsistent are released (meaning: based on a bad config, capsicain sends an 'F14 down' but never a corresponding 'F14 up'. Shouldn't happen in the first place).

If you're feeling adventurous, you can switch to the "dev" branch, and get the latest capsicain v70beta from the /x64/release/ directory. Major code changes. I've used it for two days and no issues so far, but well, people tend to do things that I never do...

**Comment by LuisSanchez-Dev** [comment]
Confirming that the dev build fixed the issue! Thanks for your hard work.
