### ISSUE TITLE
Keyboard-specific remapping

### ISSUE THREAD

**Issue by MatejKafka** [cajhin/capsicain#44]
I'd like to use an extra keyboard as a "macro pad", by remapping some keys to the F13-F24 range, while still using another keyboard as a normal keyboard, with separate keymap.

As far as I understand, Interception supports this, but this feature is not exposed by Capsicain. Would it be possible to add it?

Something similar was already discussed in issue #3, but the solution there works around the problem instead of solving it. I'm willing to get my hands dirty and make a PR for this, but it will probably require quite substantial changes to the codebase, so I'd need to discuss it with you first and get some pointers. :)

**Comment by arthurmoeller** [comment]
Any news on this? I would need it to rewire space to shift only on external keyboard

**Comment by cajhin** [comment]
Sorry for the late reply, I'm not currently doing computer stuff in my free time (great weather outside).

Today, the only way to limit capsicain remapping to a single keyboard is
https://github.com/cajhin/capsicain/wiki/Keyword%3A-OPTION#option-processonlyfirstkeyboard

It's not perfect, you have to remember to touch the "relevant" board first, every time you start up or change layers.

Making this configurable via .ini file would be quite easy
- another ini Layer Option "activeBoardID=_fooSomeIdentifier_"
  (you can hardcode your specific board for testing)
- an early check "if globalState.deviceIdKeyboard.toLower() contains _fooSomeIdentifier_ then continue"
   I would add this to capsicain.cpp, line 288, where it says
   `//ignore secondary keyboard?`. 
- on reading the ini file, everything is converted to lowercase. The ID reported by Interception is uppercase.
   

These identifiers are really ugly, I think there is no guarantee that two boards have different identifiers. It is only safe for different classes of boards (like: internal / USB / Bluetooth). To see them, turn on debug mode and press a key on each board.

Ideally, I'd want this to be flexible so that you could define n active boards for each layer.

That's all off the top of my head, I might have forgotten something.

**Comment by arthurmoeller** [comment]
Thank you for the reply. I will think about it and look into the code.

I will describe my usecase:
- I have a laptop and an external split keyboard
- left half (external) has spacebar aswell so i have 2 spacebars
- l want to use left half (external) in combination with laptop keyboard right side
- ideally i could apply same mapping to both boards + rewire specific keys on one board

**Comment by cajhin** [comment]
there is a new capsicain.exe in the x64 folder, which should implement this feature request.
See https://github.com/cajhin/capsicain/wiki/Keyword%3A-OPTION/_edit#option-includedeviceid-searchstring for details

If you try it out, then please let me know how it works for you.

**Comment by arthurmoeller** [comment]
Sorry that I wasnt more helpful in this. 
I looked at the Code briefly but never coded in C++ only php and js.

Its working exactly as described in the example. 
Thank you for the effort.

- _ideally i could apply same mapping to both boards + rewire specific keys on one board_
this is not possible or did I miss something? maybe as additonal keyword before the rewire?
`DeviceID:ven_hpq  REWIRE Y Z`

**Comment by cajhin** [comment]
Done.
You can now restrict mappings to specific keyboards, see wiki
OPTION IncludeDeviceID {searchString}

**Comment by DARKFiB3R** [comment]
How do I find the DeviceID for my macro pad?

I installed Interception as instructed (new files mouse.sys and keyboard.sys are now in C:\Windows\System32\drivers)

If I run Capsicain and press a key on the macro pad, it gives me this info: hid\vid_4355&pid_0083&rev_0001&mi_02&col03

https://i.imgur.com/53sOVjt.png

I have also used USBDeview http://www.nirsoft.net/ (as it allows me to list devices by the last time they were connected).

This is the info it gives me...

https://i.imgur.com/eXdTz0T.png

I would like to remap some keys on this pad..

Apayado YIQI K33

https://i.imgur.com/7ZbcQgv.png

For instance, I would like the END key to be TAB

I renamed capsicain.ini to king-capsicain.ini, created a new capsicain.ini with the follwing...

```
[CONFIG_1]
OPTION configName K33_fusion360
IncludeDeviceID:hid\vid_4355&pid_0083&rev_0001&mi_02&col03 REWIRE END TAB

[CONFIG_2]
OPTION ConfigName Photoshop
IncludeDeviceID:hid\vid_4355&pid_0083&rev_0001&mi_02&col03 REWIRE END H
```

How many things have I got wrong? 🤣

Hope you can help.

Thanks.
