### ISSUE TITLE
Is it possible to rewire a single key to a combination of key without a modifier?

### ISSUE THREAD

**Issue by PhyphenS** [cajhin/capsicain#58]
I have a dedicated number pad and wanted to use it to single key presses to complete a unique combined key press for hotkeys in various software (e.g pressing 1 would press F13 + Shift)

Would this be possible without having to press an additional modifier key?

**Comment by cajhin** [comment]
it's probably possible, assuming that your number pad sends "normal" key presses and not proprietary USB codes that only the manufacturer's driver understands.
There's an inconvenience since you cannot configure "this config only for the pad", so it is active on the main keyboard, too.
The workaround is Option "processOnlyFirstKeyboard". See https://github.com/cajhin/capsicain/wiki/Keyword%3A-OPTION

**Comment by PhyphenS** [comment]
Thanks for getting back to me so quick.
I was able it to activate on just the keypad using the processOnlyFirstKeyboard if I REWIRE 1 to F13. 
What I am having difficulty with is using REWIRE (or should it be COMBO?) to trigger a combination of key presses when just the 1 key was pressed (all the examples seemed to show multiple key presses to trigger different key presses)
Thank you for the help

**Comment by cajhin** [comment]
REWIRE only maps plain keys. You need a COMBO.

1 key to shift-F13:
COMBO 1 [] > moddedKey ( F13 + ...& )

If you want to produce more than one alphanumeric key (like 1 -> T E S T), look into function sequence()

**Comment by PhyphenS** [comment]
That worked perfectly!

I think my formatting was off but that is great, thank you so much for your help!
