### ISSUE TITLE
Sleep not working

### ISSUE THREAD

**Issue by dliu9999** [cajhin/capsicain#73]
Hi, is there a way to get sleep to work? I have `COMBO \ [^^^& .... ....] > key(SLEEP)` (so mod9 + `\`) but it doesn't seem to work. Thanks!

**Comment by cajhin** [comment]
I tried, but it doesn't work. Looks like Windows does not (no longer?) reacts to the SLEEP scancode.
My actual sleep buttons are not keys (like "lid closed", they send some signal that is not a key stroke).

Easiest solution is probably an Autohotkey config (AHK supports a system call for the power events, I'd rather not implement this in capsicain because it's not in focus, it's not keystrokes).

**Comment by cajhin** [comment]
Created a new wiki page and explained it

[Problems & Solutions](https://martinvanbeurden.nl/blog/virtualbox-numlock-weirdness/)
