### ISSUE TITLE
REWIRE with German keyboard and # key

### ISSUE THREAD

**Issue by yoloswaggerboy69** [cajhin/capsicain#8]
hey, don't know if I'm being dumb again, but i'm having problems remapping the # key on my german keyboard to the \ key. is this because # is used for comments? if so is there a way around this?

`REWIRE # \`

**Comment by cajhin** [comment]
Hi. The thing is, there IS no # key. The german keyboard has a keycap with a # on it, and Windows translates this to the # character, but under the hood, this is really the \ key. On ANSI keyboards that's the one over Enter.
See https://support.getfreewrite.com/article/44-freewrites-physical-keyboard-layouts-ansi-vs-iso
When you specify scancodes, you have to look at the original IBM US keyboard. All the international characters are produced by Windows, not by the keyboard.

Now I'm not sure what you want to achieve.
You have an ISO (Euro) keyboard layout, Windows set to German, but you want the key left of the enter key to produce a backslash?

**Comment by yoloswaggerboy69** [comment]
Yes i essentially want to match it to a standard qwerty layout as far as that's possible given that the hardware keys aren't exactly the same.

Is there an efficient way for me to find out what key my keyboard is sending so i know which remapping to specify in capsicain ?
Because i truly don't want to keep bothering you since you've already helped me so much.

**Comment by cajhin** [comment]
[ESC] + D  for debug mode, then you see the scancodes for all keypresses in the left column.
(note that REWIRE comes before that is logged, so you'll see the wrong code for rewired keys).

I don't mind the questions, no problem.
I postponed an answer last time because I didn't really understand the question and looked into mouse button support, and then forgot about it.

**Comment by cajhin** [comment]
If you want a standard US qwerty layout,
which comes all the special characters on different keys by the way, so Shift+2 is now @ instead of " on the German keyboard,
then the straight approach is to tell Windows you want a US layout.

I'm on a Mac right now, search for keyboard... spracheinstellungen... something like that.
You need to add "US English", and decide if German or US shall be default.
You can now switch languages with either the new little symbol in the tray bar, or with shift+alt.

If you want to stay on a German keyboard layout but map *some* english keys, that's all manual config, bit messy.

I'm just guessing though what you want to achieve.
Does Reason (Logic Pro?) have shortcuts that are working with a US keyboard in mind?
That's the reason why many German coders use US - the C language was created in the US and keys like \ { } are stupid on German keyboards

j

**Comment by yoloswaggerboy69** [comment]
yeah i actually just did that, i set it to US layout and fixed Y and Z.

now I'll just have to build the muscle memory so that i can hit the backslash and bracket keys and all that without issue.

Yeah Pro Tools is very European unfriendly [https://i.redd.it/8pwhvyj5ys261.jpg](https://i.redd.it/8pwhvyj5ys261.jpg) this is someones custom keyboard with some of the most used functions.

I sadly didn't consider this when i bought my logitech MX keys but i'll likely get one with a US layout just because all the audio and video software i use is very US centric in their keyboard shortcuts.

**Comment by cajhin** [comment]
now THOSE are some fancy keycaps :)

I actually prefer Euro keyboards with US layout - but I'm touch typing and I don't care if the labels on the keys are wrong.

Hardware US keyboards mess with your muscle memory, mostly Enter and left shift, because you cannot escape German keyboards if you live here. Also, the Z/Y flip is a pain in the butt but that's what you get when you don't agree on standards...

Good luck
j

**Comment by yoloswaggerboy69** [comment]
oh yeah good point about the shift and enter key, well anyways thank you so much for all the help, at this point I'm as close to my goal I'll get without purchasing a mac with a US keyboard so that's fantastic. 
Keep up the great work and have a nice day! :)
