### ISSUE TITLE
If I map alt to mod12, how do I implement the alt-tab function?

### ISSUE THREAD

**Issue by doit132** [cajhin/capsicain#81]

**Comment by cajhin** [comment]
The Alt-Tab combo is different and difficult, because you cannot send a single combo. You have to keep pressing Alt, and there is no ini rule that deals with that.
My own config uses the Alt keys for special characters, and "tap+hold Alt" to restore the alt key.
`REWIRE LALT  MOD12  //  LALT`

With this, I can press, release, press LALT, then press tab as often as I want, then release LALT

It's not perfect, but that way I don't have to hardcode a messy Alt+Tab behavior.
